# Generated by Django 3.2 on 2021-04-26 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecordReport', '0002_auto_20210426_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficPolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TrafficPolice',
                'verbose_name_plural': 'TrafficPolices',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.BooleanField(verbose_name='is_approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('records', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RecordReport.records')),
                ('traffic_police', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TrafficReport.trafficpolice')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
