# Generated by Django 3.2 on 2021-04-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficReport', '0002_alter_trafficpolice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.BooleanField(default=False, verbose_name='is_approved'),
        ),
        migrations.AlterField(
            model_name='trafficpolice',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
