# Generated by Django 3.2 on 2021-04-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficReport', '0003_auto_20210426_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('read_repor', 'can read report'),), 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
