# Generated by Django 3.2 on 2021-05-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecordReport', '0002_auto_20210426_1940'),
        ('TrafficReport', '0004_alter_report_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='records',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='RecordReport.records'),
        ),
    ]
