# Generated by Django 3.2 on 2021-06-01 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecordReport', '0004_alter_records_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TrafficReport', '0006_systemadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.BooleanField(default=False, verbose_name='is_reported'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('records', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RecordReport.records')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
