# Generated by Django 3.2 on 2021-06-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficReport', '0007_auto_20210601_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
