# Generated by Django 3.2 on 2021-06-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficReport', '0008_alter_notification_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
