# Generated by Django 3.2 on 2021-04-26 19:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RecordReport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_owner', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.RemoveField(
            model_name='records',
            name='vehicle_plate',
        ),
        migrations.AddField(
            model_name='records',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RecordReport.vehicle'),
            preserve_default=False,
        ),
    ]
