# Generated by Django 3.2 on 2021-05-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecordReport', '0002_auto_20210426_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='RecordReport.vehicle'),
        ),
    ]
