# Generated by Django 3.2 on 2021-06-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecordReport', '0003_alter_records_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'Records', 'verbose_name_plural': 'Records'},
        ),
    ]
